# Generated by Django 5.2.6 on 2025-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estudiante",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(
                fields=["apellido", "nombre"], name="idx_estudiante_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(fields=["estatus"], name="idx_estudiante_estatus"),
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(fields=["ciudad"], name="idx_estudiante_ciudad"),
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(fields=["email"], name="idx_estudiante_email"),
        ),
    ]
