# Generated by Django 5.2.6 on 2025-12-17 02:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_credentials_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(help_text='Número de resolución (Ej: 3601/2023)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la resolución', max_length=200)),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicación oficial')),
                ('vigente', models.BooleanField(default=True, help_text='Indica si la resolución está vigente')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la resolución')),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 17, 2, 51, 28, 841541, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='resolucion',
            field=models.ForeignKey(blank=True, help_text='Marco legal que habilita este programa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='core.resolucion'),
        ),
    ]
