# Generated by Django 5.2.6 on 2025-12-17 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_resolucion_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha_calificacion']},
        ),
        migrations.AddField(
            model_name='nota',
            name='es_nota_definitiva',
            field=models.BooleanField(default=False, help_text='True si es la nota final que cuenta para aprobar el bloque'),
        ),
        migrations.AddField(
            model_name='nota',
            name='habilitado_por',
            field=models.ForeignKey(blank=True, help_text='Nota de Final Virtual que habilitó este Final Sincrónico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilita_a', to='core.nota'),
        ),
        migrations.AddField(
            model_name='nota',
            name='intento',
            field=models.PositiveIntegerField(default=1, help_text='Número de intento para este examen (1, 2, 3...)'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['examen', 'estudiante', 'intento'], name='core_nota_examen__f5a4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['estudiante', 'es_nota_definitiva'], name='core_nota_estudia_655ce5_idx'),
        ),
    ]
