# Generated by Django 5.2.6 on 2026-02-13 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cohorte_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloque',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cohorte',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='bloquedefechas',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='orden',
        ),
        migrations.AddField(
            model_name='bloquedefechas',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la secuencia de semanas'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de esta cohorte'),
        ),
        migrations.AlterField(
            model_name='bloquedefechas',
            name='nombre',
            field=models.CharField(help_text="Nombre de la plantilla (ej: 'Estándar 8 semanas')", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='bloque_fechas',
            field=models.ForeignKey(help_text='Plantilla de calendario a usar', on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='core.bloquedefechas'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('Primaria Completa', 'Primaria Completa'), ('Secundaria Incompleta', 'Secundaria Incompleta'), ('Secundaria Completa', 'Secundaria Completa'), ('Terciaria/Universitaria Incompleta', 'Terciaria/Universitaria Incompleta'), ('Terciaria/Universitaria Completa', 'Terciaria/Universitaria Completa'), ('Terciaria/Universitaria', 'Terciaria/Universitaria')], max_length=60, verbose_name='Nivel Alcanzado'),
        ),
    ]
