# Generated by Django 5.2.6 on 2026-02-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_horariocursada'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='horariocursada',
            new_name='core_horari_cohorte_c01b0b_idx',
            old_name='core_horari_cohorte_d9ec72_idx',
        ),
        migrations.RenameIndex(
            model_name='horariocursada',
            new_name='core_horari_bloque__470ff7_idx',
            old_name='core_horari_bloque__3ca655_idx',
        ),
    ]
