# Generated by Django 5.2.6 on 2026-03-04 02:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_convert_document_links_to_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dni_tutor_digitalizado',
            field=models.FileField(blank=True, upload_to=core.models.dni_tutor_upload_path, verbose_name='DNI del Tutor digitalizado (Archivo)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota_parental_firmada',
            field=models.FileField(blank=True, upload_to=core.models.nota_parental_upload_path, verbose_name='Nota de Autorización Parental Firmada (Archivo)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI del Tutor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Tutor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estatus',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Baja', 'Baja'), ('Condicional', 'Condicional'), ('Preinscripto', 'Preinscripto')], default='Regular', max_length=15, verbose_name='Estatus de Regularidad'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('LIBRE', 'Libre')], default='INSCRIPTO', max_length=10),
        ),
    ]
