# Generated by Django 5.2.6 on 2026-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estudiante_dni_tutor_digitalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='autorizacion_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='autorizacion_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='autorizaciones/selfies/', verbose_name='Selfie de Conformidad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='autorizacion_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DIGITAL', 'Firma Digital (Selfie)'), ('MANUAL', 'Firma Manual (Papel)')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='autorizacion_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del Tutor'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('LIBRE', 'Libre'), ('PAUSADO', 'Pausado'), ('EGRESADO', 'Egresado')], default='INSCRIPTO', max_length=10),
        ),
    ]
