# Generated by Django 5.2.6 on 2026-03-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_estudiante_autorizacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('PREINSCRIPTO', 'Preinscripto'), ('CURSANDO', 'Cursando'), ('INACTIVO', 'Inactivo'), ('LIBRE', 'Libre'), ('PAUSADO', 'Pausado'), ('EGRESADO', 'Egresado'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], default='PREINSCRIPTO', max_length=20),
        ),
    ]
