# Generated by Django 5.2.6 on 2026-03-11 01:02

from django.db import migrations


def update_estados(apps, schema_editor):
    Inscripcion = apps.get_model("core", "Inscripcion")
    Inscripcion.objects.filter(estado="INSCRIPTO").update(estado="PREINSCRIPTO")
    Inscripcion.objects.filter(estado="ACTIVO").update(estado="CURSANDO")

def reverse_estados(apps, schema_editor):
    Inscripcion = apps.get_model("core", "Inscripcion")
    Inscripcion.objects.filter(estado="PREINSCRIPTO").update(estado="INSCRIPTO")
    Inscripcion.objects.filter(estado="CURSANDO").update(estado="ACTIVO")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.RunPython(update_estados, reverse_estados),
    ]
