# Generated by Django 5.2.6 on 2026-03-27 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20260310_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelacionDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('total_preguntas', models.PositiveIntegerField(default=10)),
                ('respuestas_json', models.JSONField(blank=True, help_text='Respuestas detalladas del estudiante', null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nivelacion_digital', to='core.estudiante')),
                ('modulo_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulo')),
            ],
            options={
                'verbose_name': 'Nivelación Digital',
                'verbose_name_plural': 'Nivelaciones Digitales',
            },
        ),
    ]
