# Generated by Django 5.2.6 on 2026-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_nivelaciondigital'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Archivado'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['is_active'], name='idx_estudiante_active'),
        ),
    ]
