# Generated by Django 5.2.6 on 2026-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_estudiante_archived_at_estudiante_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreinscripcionTerciario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('apellido_nombre', models.CharField(help_text='Tal cual figura en DNI', max_length=200)),
                ('dni', models.CharField(max_length=15)),
                ('cuil', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('localidad_nacimiento', models.CharField(max_length=100)),
                ('provincia_nacimiento', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('localidad', models.CharField(choices=[('ushuaia', 'Ushuaia'), ('rg_sur', 'Río Grande - Margen Sur'), ('rg_norte', 'Río Grande - Margen Norte'), ('tolhuin', 'Tolhuin'), ('zona_rural', 'Zona rural (Por ej. Estancia Cullen)'), ('otras', 'Otras Ciudades')], max_length=20)),
                ('finalizo_secundaria', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('cursando', 'Cursando el último año')], max_length=10)),
                ('posee_estudios_superiores', models.BooleanField(default=False)),
                ('estudios_superiores_finalizado', models.BooleanField(blank=True, null=True)),
                ('estudios_superiores_carrera', models.CharField(blank=True, max_length=200)),
                ('posee_pc', models.BooleanField()),
                ('posee_internet', models.BooleanField()),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('posee_discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditiva', 'Auditiva'), ('intelectual', 'Intelectual'), ('motora', 'Motora'), ('tea', 'Trastornos de Espectro Autista'), ('otra', 'Otra discapacidad'), ('multiple', 'Más de una discapacidad')], max_length=20)),
                ('posee_cud', models.BooleanField(blank=True, null=True)),
                ('apoyo_inclusion', models.CharField(blank=True, choices=[('estatal', 'Sector Estatal'), ('privado', 'Sector Privado'), ('ninguno', 'Ninguno')], max_length=10)),
                ('requiere_apoyo_especifico', models.BooleanField(blank=True, null=True)),
                ('descripcion_apoyo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Preinscripción Terciario',
                'verbose_name_plural': 'Preinscripciones Terciario',
                'ordering': ['-created_at'],
            },
        ),
    ]
