# Generated by Django 5.2.6 on 2026-05-21 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_preinscripcion_terciario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='dni_digitalizado',
            field=models.FileField(blank=True, null=True, upload_to='terciario/dni/'),
        ),
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='hd_inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscripcion_terciario', to='core.inscripcion'),
        ),
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='titulo_digitalizado',
            field=models.FileField(blank=True, null=True, upload_to='terciario/titulo/'),
        ),
    ]
