# Generated by Django 5.2.6 on 2026-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_preinscripcion_terciario_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPreinscripcionTerciario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preinscripcion_abierta', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('mensaje_cierre', models.CharField(blank=True, default='Las preinscripciones están cerradas en este momento.', max_length=300)),
            ],
            options={
                'verbose_name': 'Configuración Preinscripción Terciario',
            },
        ),
    ]
