# Generated by Django 5.2.6 on 2026-05-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_configuracion_preinscripcion_terciario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpreinscripcionterciario',
            name='hd_cohorte',
            field=models.ForeignKey(blank=True, help_text='Cohorte de HD Módulo 2 donde se inscriben los aprobados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_terciario', to='core.cohorte'),
        ),
    ]
