# Generated by Django 5.2.6 on 2026-05-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_hd_cohorte_to_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionpreinscripcionterciario',
            name='programa_terciario',
            field=models.ForeignKey(blank=True, help_text='Programa terciario al que aplica esta configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracion_preinscripcion', to='core.programa'),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='bloque',
            field=models.ForeignKey(default=1, help_text='Bloque académico al que aplica esta cohorte', on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='core.bloque'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estatus',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Baja', 'Baja'), ('Condicional', 'Condicional'), ('Preinscripto', 'Preinscripto')], default='Preinscripto', max_length=15, verbose_name='Estatus de Regularidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='examen',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='examen',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gt', 0)), name='check_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('examen', 'estudiante', 'intento'), name='uniq_nota_examen_estudiante_intento'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(condition=models.Q(('es_nota_definitiva', True)), fields=('examen', 'estudiante'), name='uniq_nota_definitiva_por_examen_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('calificacion__gte', 0), ('calificacion__lte', 10)), name='check_calificacion_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='preinscripcionterciario',
            constraint=models.UniqueConstraint(fields=('dni',), name='uniq_preinscripcion_dni'),
        ),
        migrations.AddConstraint(
            model_name='preinscripcionterciario',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_preinscripcion_email'),
        ),
    ]
