# Generated by Django 5.2.6 on 2026-05-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_configuracionpreinscripcionterciario_programa_terciario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='bloque',
            field=models.ForeignKey(help_text='Bloque académico al que aplica esta cohorte', on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='core.bloque'),
        ),
    ]
