# Generated by Django 5.2.6 on 2026-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_cohorte_bloque'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examen',
            constraint=models.UniqueConstraint(fields=('modulo', 'tipo_examen'), name='uniq_examen_modulo_tipo'),
        ),
        migrations.AddConstraint(
            model_name='examen',
            constraint=models.UniqueConstraint(fields=('bloque', 'tipo_examen'), name='uniq_examen_bloque_tipo'),
        ),
    ]
