# Generated by Django 5.2.6 on 2026-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_examen_uniq_examen_modulo_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinscripcionterciario',
            name='apellido_nombre',
        ),
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='apellido',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='nombre',
            field=models.CharField(default='', max_length=120),
        ),
    ]
