# Generated by Django 5.2.6 on 2026-06-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_split_apellido_nombre_preinscripcion_terciario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='correo_bienvenida_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que se envió el correo de bienvenida', null=True),
        ),
        migrations.AddField(
            model_name='preinscripcionterciario',
            name='correo_correccion_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que se envió el correo de corrección de Hoja de Ruta', null=True),
        ),
    ]
