# Generated by Django 5.2.15 on 2026-06-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_email_tracking_terciario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPreinscripcionVideojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preinscripcion_abierta', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('mensaje_cierre', models.CharField(blank=True, default='Las preinscripciones de Videojuegos están cerradas en este momento.', max_length=300)),
                ('cohorte_activa', models.ForeignKey(blank=True, help_text='Cohorte activa de Videojuegos donde se inscriben los aprobados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_videojuegos', to='core.cohorte')),
            ],
            options={
                'verbose_name': 'Configuración Preinscripción Videojuegos',
            },
        ),
    ]
