# Generated by Django 5.2.15 on 2026-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_configuracionpreinscripcionvideojuegos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='preinscripcionterciario',
            name='uniq_preinscripcion_email',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(help_text='Correo Electrónico', max_length=254),
        ),
    ]
