# Generated by Django 5.2.15 on 2026-06-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_preinscripcionterciario_uniq_preinscripcion_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(help_text='Correo Electrónico', max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='preinscripcionterciario',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_preinscripcion_email'),
        ),
    ]
